name: gotit
description: Find Your Lost Belongs.
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: ^4.0.5345
  flushbar: ^1.6.0

  dio: ^3.0.8
  shared_preferences: '>=0.5.0+0 <2.0.0'
  intl: ^0.16.1
  path: ^1.6.4
  image_picker: ^0.6.7+2
  rating_bar: ^0.2.0
  timeago: ^2.0.26
  carousel_slider: ^2.2.1
  cached_network_image: ^2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/salah.jpg
  - assets/images/Capture.JPG
  - assets/images/crying_cat.jpg
  - assets/images/Sheka.jpeg
  - assets/images/Sheka.jpg
  - assets/images/logo.png
  - assets/images/app_bar_logo.png
  - assets/images/landing_logo.png
  - assets/images/app_logo.png
  - assets/images/no_notifications.png
  - assets/images/no_items.png
  - assets/images/no_messages.png
  - assets/images/landing.png
  - assets/images/no_requests.png
  - assets/images/user.jpg
